homevisitportal/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('visits/', include('visits.urls')),
    path('', RedirectView.as_view(url='/visits/', permanent=True)),
]

# django.contrib.auth.urls:
#  accounts/ login/ [name='login']
#  accounts/ logout/ [name='logout']
#  accounts/ password_change/ [name='password_change']
#  accounts/ password_change/done/ [name='password_change_done']
#  accounts/ password_reset/ [name='password_reset']
#  accounts/ password_reset/done/ [name='password_reset_done']
#  accounts/ reset/<uidb64>/<token>/ [name='password_reset_confirm']
#  accounts/ reset/done/ [name='password_reset_complete']
urlpatterns += [
    path('accounts/login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('accounts/', include('django.contrib.auth.urls')),
]

# If not using django.contrib.staticfiles app:
#
# from django.conf import settings
# from django.conf.urls.static import static
#
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

visits/urls.py
from django.urls import path
from . import views

app_name = 'visits'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('create/', views.CreateView.as_view(), name='create'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/update/', views.UpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.DeleteView.as_view(), name='delete'),
    path('help/', views.help_page, name='help'),
]

timelogger/models.py
from django.contrib.auth import get_user_model
from django.db import models


class Client(models.Model):
    first_name = models.CharField(max_length=500)
    last_name = models.CharField(max_length=500)
    city = models.CharField(max_length=500)
    county = models.CharField(max_length=500)


class Visit(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    visit_date = models.DateTimeField()
    duration = models.IntegerField()

visits/models.py
from django.contrib.auth import get_user_model
from django.db import models


class Client(models.Model):
    first_name = models.CharField(max_length=500)
    last_name = models.CharField(max_length=500)
    city = models.CharField(max_length=500)
    county = models.CharField(max_length=500)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class Visit(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    visit_date = models.DateTimeField()
    duration = models.IntegerField()

    def __str__(self):
        return f'{self.client} on {self.visit_date}'

visits/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.shortcuts import render
from django.views import generic
from .models import Visit


def help_page(request):
    return render(request, 'visits/help.html')


class IndexView(LoginRequiredMixin, generic.ListView):
    template_name = 'visits/index.html'
    context_object_name = 'recent_visits'

    def get_queryset(self):
        return Visit.objects.order_by('-visit_date')[:50]


class CreateView(LoginRequiredMixin, generic.CreateView):
    model = Visit
    template_name = 'visits/create.html'
    fields = ['client', 'visit_date', 'duration']
    success_url = reverse_lazy('visits:index')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class DetailView(LoginRequiredMixin, generic.DetailView):
    model = Visit
    template_name = 'visits/detail.html'


class UpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Visit
    template_name = 'visits/update.html'
    fields = ['visit_date', 'duration']
    success_url = reverse_lazy('visits:index')


class DeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Visit
    template_name = 'visits/delete.html'
    success_url = reverse_lazy('visits:index')

homevisitportal/templates/base_bulma.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Home Visit Portal</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>

  {% load static %}
  <script src="{% static 'js/site.js' %}"></script>
</head>

<body>

<!-- Only show navbar if the user is logged in -->
{% if user.is_authenticated %}
<nav class="navbar is-transparent">
  <div class="navbar-brand">
    <a class="navbar-item" href="https://bulma.io">
      <img src="https://bulma.io/images/bulma-logo.png" alt="Bulma: a modern CSS framework based on Flexbox" width="112" height="28">
    </a>
    <div class="navbar-burger burger" data-target="navbarExampleTransparentExample">
      <span></span>
      <span></span>
      <span></span>
    </div>
  </div>

  <div id="navbarExampleTransparentExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item" href="{% url 'visits:index' %}">
        Home
      </a>
      <a class="navbar-item" href="{% url 'logout' %}">
        Logout
      </a>
      <!-- Dropdown menu within the navbar -->
      <!--<div class="navbar-item has-dropdown is-hoverable">-->
        <!--<a class="navbar-link" href="/documentation/overview/start/">-->
          <!--Docs-->
        <!--</a>-->
        <!-- Puts a horizontal divider in the dropdown -->
        <!--<div class="navbar-dropdown is-boxed">-->
          <!--<a class="navbar-item" href="/documentation/overview/start/">-->
            <!--Overview-->
          <!--</a>-->
          <!--<a class="navbar-item" href="https://bulma.io/documentation/modifiers/syntax/">-->
            <!--Modifiers-->
          <!--</a>-->
          <!--<a class="navbar-item" href="https://bulma.io/documentation/columns/basics/">-->
            <!--Columns-->
          <!--</a>-->
          <!--<a class="navbar-item" href="https://bulma.io/documentation/layout/container/">-->
            <!--Layout-->
          <!--</a>-->
          <!--<a class="navbar-item" href="https://bulma.io/documentation/form/general/">-->
            <!--Form-->
          <!--</a>-->
          <!--<hr class="navbar-divider">-->
          <!--<a class="navbar-item" href="https://bulma.io/documentation/elements/box/">-->
            <!--Elements-->
          <!--</a>-->
          <!--<a class="navbar-item is-active" href="https://bulma.io/documentation/components/breadcrumb/">-->
            <!--Components-->
          <!--</a>-->
        <!--</div>-->
      </div>
    </div>
  </div>
</nav>
{% endif %}

{% block content %}
{% endblock %}
</body>

</html>

visits/templates/visits/create.html
{% extends 'base_bulma.html' %}

{% block content %}

<div class="section">
  <form method="post">
    {% csrf_token %}

    {{ form.non_field_errors }}
    {{ form.errors }}

    <div class="field">
      <label class="label">Client</label>
      <div class="control">
        <div class="select">
          <select name="{{ form.client.name }}" id="{{ form.client.auto_id }}" required>
            {% for value, text in form.client.field.choices %}
              <option value="{{ value }}">{{ text }}</option>
            {% endfor %}
          </select>
        </div>
      </div>
    </div>

    <div class="field">
      <label class="label">Visit Date</label>
      <div class="control">
        <input name="{{ form.visit_date.name }}" id="{{ form.visit_date.auto_id }}" class="input is-info" type="text" required>
      </div>
    </div>

    <div class="field">
      <label class="label">Visit Date</label>
      <div class="control">
        <input name="{{ form.duration.name }}" id="{{ form.duration.auto_id }}" class="input is-info" type="number" required>
      </div>
    </div>

    <input class="button is-primary" type="submit" value="Save">
  </form>
</div>

{% endblock %}

<!--

Automatic rendering of the entire inner form (not recommended):
{{ form.as_p }}      # Render the inner form as simple p tags
{{ form.as_ul }}     # Render the inner form as a simple list
{{ form.as_table }}  # Render the inner form as a simple table

The fields are accessible by iterating over the form (probably not recommended):
{% for field in form %}  # Iterate over all fields
  {{ field }}
{% endfor %}

{% for field in form.visible_fields %}  # Iterate over only the visible fields
  {{ field }}
{% endfor %}

{% for field in form.hidden_fields %}  # Iterate over only the hidden fields
  {{ field }}
{% endfor %}

These ideas seem nice, but I really don't like losing the flexibility
of being able to style things exactly how I want them. I love Django's
Model system, its ORM, and the automatic Form handling, but auto-generating
HTML based on a model sacrifices too much flexibility compared to the
value that it adds.

Automatically render an entire form and make it fussy to specify all the styling
attributes in the code? Have to use a 3rd party library to _nicely_ customize the CSS
of these elements? I'd really rather write the entire form myself and manually link
to the form fields by name. If I miss one or incorrectly name something, then that's
my own fault and I'll fix it. As a I said, I really love the automatic Form binding /
handling and I want to keep that feature. I just don't want any HTML rendering to occur
that isn't under my (and subsequently Bulma's) control.

Field-level errors (also accessible via the individual fields, so not recommended?)
{{ form.errors }}                # Renders errors in some simple HTML (not recommended)
{{ form.errors.as_json }}        # Collect all the form errors as a JSON object
{{ form.errors.name_of_field }}  # Get the errors for a specific field

I also really don't want to have to write any sort of styling info outside of the
HTML templates. The library django-widget-tweaks helps this to an extent, but
it had at least one bug that made it unusable (it wasn't properly replacing the 'type'
attribute on input tags). In the end, and after digging through the docs for a while,
I found that facilities do exist to utilize Django's Form system without sacrificing
the HTML flexibility.



Now this is what I'm after. I want all of this information to be in one place for future
reference. This is all the knowledge necessary to wire my custom HTML up to Django's handy
Form handling system. This gives me best of both worlds. This is the level of abstraction
that I prefer to work at.

Form-level errors:
{{ form.non_field_errors }}

Each field is available as an attribute of the form using:
{{ form.name_of_field }}

Field attributes:
{{ form.name_of_field }}               # Renders the entire field: label and input (not recommended)
{{ form.name_of_field.auto_id }}       # HTML ID attribute
{{ form.name_of_field.name }}          # Name of this field in the form
{{ form.name_of_field.value }}         # Current value of this field
{{ form.name_of_field.label }}         # Name of this field's label
{{ form.name_of_field.label_tag }}     # Rendered label tag for this field (not recommended)
{{ form.name_of_field.id_for_label }}  # Links a label to its input field
{{ form.name_of_field.help_text }}     # Help text for the field (comes from the model?)
{{ form.name_of_field.html_name }}     # HTML name attribute
{{ form.name_of_field.is_hidden }}     # True if this field is hidden, else False
{{ form.name_of_field.data }}          # Data bound to this field
{{ form.name_of_field.errors }}        # Iterable of form errors

Attributes specific to certain types of fields:
{{ form.name_of_field.field }}

CharField:
{{ form.name_of_char_field.field.max_length }}  # Maximum length of this field
{{ form.name_of_char_field.field.min_length }}  # Minimum length of this field

ChoiceField:
{{ form.name_of_choice_field.field.choices }}  # Iterable of (key, value) choices for this field

TODO: Other specific field attributes

-->

visits/templates/visits/delete.html
<form method="post">
  {% csrf_token %}
  <p>Are you sure you want to delete "{{ visit }}"?</p>
  <input type="submit" value="Confirm">
</form>

visits/templates/visits/detail.html
<h1>Some visit detail message</h1>

<p>{{ visit.user }}</p>
<p>{{ visit.client }}</p>
<p>{{ visit.visit_date }}</p>
<p>{{ visit.duration }}</p>

<a href="{% url 'visits:update' visit.id %}">Update</a>
<br>
<a href="{% url 'visits:delete' visit.id %}">Delete</a>

visits/templates/visits/help.html
{% extends "base_bulma.html" %}

{% block content %}

<div class="section">
  <p>Put some docs here?</p>
</div>

{% endblock %}

visits/templates/visits/index.html
{% extends 'base_bulma.html' %}

{% block content %}

<div class="section">
  <div class="container">
    <div class="column is-6 is-offset-3">
      {% if recent_visits %}
        {% for visit in recent_visits %}
          <a class="box" href="{% url 'visits:detail' visit.id %}">
            {{ visit.client }} on {{ visit.visit_date }}
          </a>
        {% endfor %}
      {% else %}
        <p>No visits are available.</p>
      {% endif %}
      <a class="button is-primary" href="{% url 'visits:create' %}">Add Visit</a>
    </div>
  </div>

</div>

{% endblock %}

visits/templates/visits/update.html
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Update">
</form>